"""empty message

Revision ID: 36acb2aa4175
Revises: cb1849e3ec92
Create Date: 2020-05-29 19:29:46.327711

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '36acb2aa4175'
down_revision = 'cb1849e3ec92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Upcoming_Shows')
    op.drop_table('Past_Shows')
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.alter_column('Artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.alter_column('Artist', 'past_shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Artist', 'upcoming_shows_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('Artist', 'genre')
    op.alter_column('Shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.drop_column('Venue', 'genre')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.drop_column('Venue', 'genres')
    op.alter_column('Shows', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Shows', 'artist_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('Artist', sa.Column('genre', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.alter_column('Artist', 'upcoming_shows_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Artist', 'past_shows_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Artist', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    op.drop_column('Artist', 'genres')
    op.create_table('Past_Shows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Past_Shows_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Past_Shows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='Past_Shows_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Past_Shows_pkey')
    )
    op.create_table('Upcoming_Shows',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Upcoming_Shows_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('artist_name', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('start_time', sa.VARCHAR(length=15), autoincrement=False, nullable=True),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Upcoming_Shows_artist_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='Upcoming_Shows_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Upcoming_Shows_pkey')
    )
    # ### end Alembic commands ###
